### PR TITLE
Use `bip21` crate

### LINKED ISSUE #12: Support query params in endpoint
this line of code

https://github.com/Kixunil/payjoin/blob/70d97ecab05088b53bf26a0d9dba8e03aa6d42ab/bip78/src/sender/mod.rs#L399

triggered me some suspect about the sanity of the endpoint string, is it already free of `?` ?

unfortunately at the moment, this code passes:

```
let uri = Uri::from_str("bitcoin:TB1Q6D3A2W975YNY0ASUVD9A67NER4NKS58FF0Q8G4?amount=1&pj=http://example.com?ciao").unwrap();
assert_eq!(uri.endpoint, "http://example.com?ciao");
```

So we are not yet performing a sanity check on it.

we should probably decide on #3 before fixing this

### PR DESCRIPTION
**Pull request by Kixunil**
This switches internal implementation of BIP 21 to the dedicated `bip21`
crate. API-breaking.

Since I forgot to pull master and had to rebase this also led to update of dependencies (regenarating `Cargo.toml`) and unplanned revert of `core_rpc` to `bitcoincore_rpc`. I think those changes are fine.

Fixes #12

### CODE REVIEW

**Comment by Kixunil** [comment]
Damn, fixing those versions is pain. Do we still want to support 1.41? 1.48 is in Debian stable...

**Comment by Kixunil** [comment]
@RCasatta could you please at least confirm/deny that you intend to review this?

**Comment by RCasatta** [comment]
@Kixunil Sorry I can't review at the moment

**Comment by Kixunil** [comment]
OK, I will merge this to not stall development. Feel free to review at any time. It's not officially stable anyway. :)

**Pull request merged**
